# Generated by Django 2.2.6 on 2019-11-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='New',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='tutorial_content',
            new_name='new_content',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='tutorial_publish',
            new_name='new_publish',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='tutorial_title',
            new_name='new_title',
        ),
    ]
