# Generated by Django 2.2.6 on 2019-11-04 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191103_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 16, 47, 19, 461692), verbose_name='date published'),
        ),
    ]
